name: ✨ Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      placeholder: "It's hard to do X when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "It would help if Treehopper could..."

  - type: checkboxes
    id: contribute
    attributes:
      label: Would you like to contribute?
      options:
        - label: I can help implement this
        - label: I can help test this
